return {
	Enable = 1,
	EnableVip = { 1, 1, 1, 1 },
	Command = "/autopost",
	String = "[AutoPost] %s:%s",
	Level = 100,
	Money = 2000000,
	Reset = 0,
	MasterReset = 0,
	PostColor = 3,
	Timer = 10,
	MESSAGES = {
		[1] = { ["Por"] = "[Sistema] Auto post ativado.", 
			["Eng"] = "[System] Auto post enable.",
			["Spn"] = "[Sistema] Publicación automática abilitada." },
		[2] = { ["Por"] = "[Sistema] Auto post desativado.", 
			["Eng"] = "[System] Auto post disabled.",
			["Spn"] = "[Sistema] Publicación automática inhabilitada." },
		[3] = { ["Por"] = "[Sistema] Você precisa estar acima do level %d para utilizar o auto post.", 
			["Eng"] = "[System] You need to be above level %d to use auto post",
			["Spn"] = "[Sistema] Debes estar por encima del nivel %d para usar la publicación automática" },
		[4] = { ["Por"] = "[Sistema] Você precisa de %d zen para utilizar o auto post.", 
			["Eng"] = "[System] You need %d zen to use the auto post",
			["Spn"] = "[Sistema] Necesitas %d zen para usar la publicación automática" },
		[5] = { ["Por"] = "[Sistema] Somente usuários vip podem usar este comando!", 
			["Eng"] = "[System] Only VIP users can use this command!",
			["Spn"] = "[Sistema] ¡Solo los usuarios VIP pueden usar este comando!" },
		[6] = { ["Por"] = "[Sistema] Você precisa de %d resets para utilizar o auto post", 
			["Eng"] = "[System] You need %d resets to use the auto post",
			["Spn"] = "[Sistema] Necesitas %d restablecimientos para usar la publicación automática" },
		[7] = { ["Por"] = "[Sistema] Você precisa de %d M.Resets para utilizar o auto post", 
			["Eng"] = "[System] You need %d M.Resets to use the auto post",
			["Spn"] = "[Sistema] Necesitas %d M.Resets para usar la publicación automática" },
		},
}